# Generated by Django 4.1.4 on 2022-12-28 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipes'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.IntegerField(choices=[(0, 'GRAM'), (1, 'MILLILITRE'), (2, 'DONA')]),
        ),
    ]
