# Generated by Django 4.1.4 on 2022-12-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipes_slug_alter_recipeingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
