# Generated by Django 4.1.4 on 2023-01-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='author',
        ),
    ]
